<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Tvoice</AssemblyName>
    <RootNamespace>Tvoice.Windows</RootNamespace>
    <ApplicationIcon>Assets\Tvoice.ico</ApplicationIcon>
    <Version>1.1.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3537.50" />
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\Tvoice.ico" />
    <Resource Include="Assets\Tvoice.png" />
    <Content Include="Web\video.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
